# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ec186ab1d8277f28b4de6b0ddc1fe17987657ab0b6e3472615762eee7af288a6ac77a698a8128d36aee63293eb9e850636c9996b52fb00048578796843d9005

test:
  secret_key_base: 0e937c6e69e77aa9cc1e936a405108bbdd56bb2714b9257ad6f837bd4bc016676fd12f70e3f501f0b97cef76cd43d715cf8eaed642e8f39728a2e39f8e4c1d73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
